version: '3'
services:
  redisedge:
    build: ./redisedge
    ports:
      - 6379:6379
  init:
    build: ./app
    depends_on:
      - redisedge
    command: ['init.py', '--url', 'redis://redisedge:6379']
  capture:
    build: ./app
    depends_on:
      - init
    # To capture from a webcam, uncomment the next lines
    # devices:
    #  - /dev/video0:/dev/video0
    # command: ['capture.py', '--url', 'redis://redisedge:6379']
    command: ['capture.py', '--url', 'redis://redisedge:6379', 'data/countvoncount2.mp4']
